# Generated by Django 4.2.4 on 2024-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
