# Generated by Django 4.2.4 on 2024-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="add_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("product_description", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("old_price", models.CharField(max_length=50)),
                ("rating", models.CharField(max_length=50)),
                ("out_of", models.CharField(max_length=50)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="productimage"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="productimage"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="productimage"),
                ),
            ],
        ),
    ]
