# Generated by Django 4.2.4 on 2024-08-22 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ds", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="add_product",
            name="image3",
        ),
    ]
